version: '3.3'
networks:
  backend:
    driver: bridge
services:
  app:
    image: abanktesapp:latest
    container_name: web-app
    build: .
    ports:
      - "8080:8080"
    networks:
      - backend